version: '3'
services:
  svelte:
    build: 
      context: .
      dockerfile: Dockerfile
    image: node-dev-svelte:1.0
    tty: true
    volumes:
      - ../:/workspace
    ports:
      - "3000:3000"